// Middleware to check if the /student/getData is the admin only...

function adminSender(req, res, next) {
    // Extracting input data...
    const admin = req.body.name;
    const id = req.body.id;

    // Checking if admin...
    if(admin === "Vishu Kalier" && id === "18082003")
        next();     // Move to the function call (middleware passed)...
    else    // Otherwise mark as access denied...
        res.status(403).json({error : "Access denied : Invalid Credentials !!"});
}

// Importing the Middleware...

module.exports = adminSender;